import { MigrationInterface, QueryRunner } from "typeorm";

export class PaymentEntity1752415370116 implements MigrationInterface {
    name = 'PaymentEntity1752415370116'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "payment_entity" ("paymentId" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "purchaseId" character varying NOT NULL, "reference" character varying NOT NULL, "amount" integer NOT NULL, "productAmount" integer NOT NULL, "deliveryFee" integer NOT NULL, "driverShare" integer NOT NULL, "platformCommission" integer NOT NULL, "dealerSubAccount" character varying NOT NULL, "dealersWalletAccount" character varying NOT NULL, "driversWalletAccount" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "createdAt" TIMESTAMP NOT NULL, "metadata" jsonb NOT NULL, CONSTRAINT "PK_cc8f21e857118bf6a1dd2d2d717" PRIMARY KEY ("paymentId"))`);
        await queryRunner.query(`CREATE TABLE "withdrawal_request_entity" ("requestId" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" character varying NOT NULL, "userId" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL, "updatedAt" TIMESTAMP, "withdrawalStatus" character varying NOT NULL DEFAULT 'pending', "metadata" jsonb NOT NULL, CONSTRAINT "PK_ff78f0cc33ec0e81069aebed619" PRIMARY KEY ("requestId"))`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" ADD "deliveryFee" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" DROP COLUMN "productId"`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" ADD "productId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" DROP COLUMN "priceType"`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_entity_pricetype_enum" AS ENUM('cylinder_price', 'custom_price')`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" ADD "priceType" "public"."purchase_entity_pricetype_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" DROP COLUMN "cylinder"`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_entity_cylinder_enum" AS ENUM('3kg', '5kg', '6kg', '12.5kg', '25kg', '50kg')`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" ADD "cylinder" "public"."purchase_entity_cylinder_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" DROP COLUMN "purchaseType"`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_entity_purchasetype_enum" AS ENUM('debut order', ' cylinder swap order ', 'gas swap order', 'commission order')`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" ADD "purchaseType" "public"."purchase_entity_purchasetype_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" DROP COLUMN "buyerId"`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" ADD "buyerId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "buyer_entity" ADD CONSTRAINT "UQ_26592e7cae06b9ca8acb493d0b9" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "buyer_entity" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "buyer_entity" ADD "location" jsonb NOT NULL`);
        await queryRunner.query(`ALTER TABLE "buyer_entity" ALTER COLUMN "isAdmin" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "buyer_entity" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "buyer_entity" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_entity" ALTER COLUMN "productId" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "product_entity" DROP COLUMN "scale"`);
        await queryRunner.query(`CREATE TYPE "public"."product_entity_scale_enum" AS ENUM('Bulk-Scale', 'Large-Scale', 'Medium-Scale', 'Small-Scale')`);
        await queryRunner.query(`ALTER TABLE "product_entity" ADD "scale" "public"."product_entity_scale_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_entity" DROP COLUMN "pricePerKg"`);
        await queryRunner.query(`ALTER TABLE "product_entity" ADD "pricePerKg" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_entity" DROP COLUMN "rating"`);
        await queryRunner.query(`ALTER TABLE "product_entity" ADD "rating" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_entity" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "product_entity" ADD "location" jsonb NOT NULL DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "product_entity" ALTER COLUMN "linkedDrivers" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_entity" ALTER COLUMN "linkedDrivers" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "product_entity" ALTER COLUMN "reviews" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_entity" ALTER COLUMN "reviews" SET DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE "product_entity" DROP COLUMN "purchases"`);
        await queryRunner.query(`ALTER TABLE "product_entity" ADD "purchases" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dealer_entity" ALTER COLUMN "dealerId" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "dealer_entity" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "dealer_entity" ADD "location" jsonb NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dealer_entity" DROP COLUMN "rating"`);
        await queryRunner.query(`ALTER TABLE "dealer_entity" ADD "rating" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dealer_entity" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "dealer_entity" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driver_entity" ALTER COLUMN "driverId" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "driver_entity" DROP COLUMN "vehicle"`);
        await queryRunner.query(`CREATE TYPE "public"."driver_entity_vehicle_enum" AS ENUM('tricycle', 'truck', 'van')`);
        await queryRunner.query(`ALTER TABLE "driver_entity" ADD "vehicle" "public"."driver_entity_vehicle_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driver_entity" ADD CONSTRAINT "UQ_5cb022ddf954bb984e749b914f8" UNIQUE ("vehicleNumber")`);
        await queryRunner.query(`ALTER TABLE "driver_entity" ADD CONSTRAINT "UQ_e40f2d324b993146b343f23bf0c" UNIQUE ("driversLicenseNumber")`);
        await queryRunner.query(`ALTER TABLE "driver_entity" ALTER COLUMN "isAdmin" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "driver_entity" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "driver_entity" ADD "userId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "auth_entity" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "auth_entity" ADD CONSTRAINT "UQ_a81b82d945ae1549f6cfe4126d4" UNIQUE ("email")`);
        await queryRunner.query(`ALTER TABLE "auth_entity" ALTER COLUMN "isAdmin" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "fmg_notification_entity" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "fmg_notification_entity" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "user_notification_entity" ALTER COLUMN "notificationId" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user_notification_entity" ALTER COLUMN "location" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_notification_entity" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "user_notification_entity" ADD "metadata" jsonb`);
        await queryRunner.query(`ALTER TABLE "user_notification_entity" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "user_notification_entity" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "token_entity" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "token_entity" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "token_entity" DROP COLUMN "verifiedAt"`);
        await queryRunner.query(`ALTER TABLE "token_entity" ADD "verifiedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "token_entity" DROP COLUMN "expiresAt"`);
        await queryRunner.query(`ALTER TABLE "token_entity" ADD "expiresAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "token_entity" ALTER COLUMN "verificationStatus" SET DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "token_entity" ALTER COLUMN "userId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_log_entity" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "audit_log_entity" ADD "createdAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sub_account_entity" ALTER COLUMN "subAccountId" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "sub_account_entity" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "sub_account_entity" ADD "createdAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sub_account_entity" ALTER COLUMN "metadata" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" DROP CONSTRAINT "wallet_entity_pkey"`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" DROP COLUMN "walletId"`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" ADD "walletId" uuid NOT NULL DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" ADD CONSTRAINT "PK_720698d81723e7d7c0d964332a2" PRIMARY KEY ("walletId")`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" ALTER COLUMN "status" SET DEFAULT 'inactive'`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" DROP COLUMN "balance"`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" ADD "balance" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" DROP COLUMN "previousBalance"`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" ADD "previousBalance" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" ADD "createdAt" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" ADD "updatedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" ADD CONSTRAINT "FK_205401c30a8eadd8e0d1a396984" FOREIGN KEY ("buyerId") REFERENCES "buyer_entity"("buyerId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buyer_entity" ADD CONSTRAINT "FK_8f58a7103b24c8194960e0a07c3" FOREIGN KEY ("userId") REFERENCES "auth_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_entity" ADD CONSTRAINT "FK_3b93559966f9ee184b0b5771b26" FOREIGN KEY ("dealerId") REFERENCES "dealer_entity"("dealerId") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dealer_entity" ADD CONSTRAINT "FK_38fd1f27cbee30fa25832f41086" FOREIGN KEY ("userId") REFERENCES "auth_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "driver_entity" ADD CONSTRAINT "FK_99091c956b0312fb0683a2938d9" FOREIGN KEY ("userId") REFERENCES "auth_entity"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "driver_entity" DROP CONSTRAINT "FK_99091c956b0312fb0683a2938d9"`);
        await queryRunner.query(`ALTER TABLE "dealer_entity" DROP CONSTRAINT "FK_38fd1f27cbee30fa25832f41086"`);
        await queryRunner.query(`ALTER TABLE "product_entity" DROP CONSTRAINT "FK_3b93559966f9ee184b0b5771b26"`);
        await queryRunner.query(`ALTER TABLE "buyer_entity" DROP CONSTRAINT "FK_8f58a7103b24c8194960e0a07c3"`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" DROP CONSTRAINT "FK_205401c30a8eadd8e0d1a396984"`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" ADD "updatedAt" date`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" ADD "createdAt" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" DROP COLUMN "previousBalance"`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" ADD "previousBalance" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" DROP COLUMN "balance"`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" ADD "balance" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" DROP CONSTRAINT "PK_720698d81723e7d7c0d964332a2"`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" DROP COLUMN "walletId"`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" ADD "walletId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "wallet_entity" ADD CONSTRAINT "wallet_entity_pkey" PRIMARY KEY ("walletId")`);
        await queryRunner.query(`ALTER TABLE "sub_account_entity" ALTER COLUMN "metadata" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sub_account_entity" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "sub_account_entity" ADD "createdAt" date NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sub_account_entity" ALTER COLUMN "subAccountId" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "audit_log_entity" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "audit_log_entity" ADD "createdAt" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "token_entity" ALTER COLUMN "userId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "token_entity" ALTER COLUMN "verificationStatus" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "token_entity" DROP COLUMN "expiresAt"`);
        await queryRunner.query(`ALTER TABLE "token_entity" ADD "expiresAt" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "token_entity" DROP COLUMN "verifiedAt"`);
        await queryRunner.query(`ALTER TABLE "token_entity" ADD "verifiedAt" character varying`);
        await queryRunner.query(`ALTER TABLE "token_entity" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "token_entity" ADD "createdAt" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_notification_entity" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "user_notification_entity" ADD "createdAt" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_notification_entity" DROP COLUMN "metadata"`);
        await queryRunner.query(`ALTER TABLE "user_notification_entity" ADD "metadata" jsonb array`);
        await queryRunner.query(`ALTER TABLE "user_notification_entity" ALTER COLUMN "location" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_notification_entity" ALTER COLUMN "notificationId" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "fmg_notification_entity" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "fmg_notification_entity" ADD "createdAt" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "auth_entity" ALTER COLUMN "isAdmin" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "auth_entity" DROP CONSTRAINT "UQ_a81b82d945ae1549f6cfe4126d4"`);
        await queryRunner.query(`ALTER TABLE "auth_entity" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "driver_entity" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "driver_entity" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driver_entity" ALTER COLUMN "isAdmin" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "driver_entity" DROP CONSTRAINT "UQ_e40f2d324b993146b343f23bf0c"`);
        await queryRunner.query(`ALTER TABLE "driver_entity" DROP CONSTRAINT "UQ_5cb022ddf954bb984e749b914f8"`);
        await queryRunner.query(`ALTER TABLE "driver_entity" DROP COLUMN "vehicle"`);
        await queryRunner.query(`DROP TYPE "public"."driver_entity_vehicle_enum"`);
        await queryRunner.query(`ALTER TABLE "driver_entity" ADD "vehicle" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "driver_entity" ALTER COLUMN "driverId" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "dealer_entity" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "dealer_entity" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dealer_entity" DROP COLUMN "rating"`);
        await queryRunner.query(`ALTER TABLE "dealer_entity" ADD "rating" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dealer_entity" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "dealer_entity" ADD "location" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dealer_entity" ALTER COLUMN "dealerId" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "product_entity" DROP COLUMN "purchases"`);
        await queryRunner.query(`ALTER TABLE "product_entity" ADD "purchases" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_entity" ALTER COLUMN "reviews" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "product_entity" ALTER COLUMN "reviews" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_entity" ALTER COLUMN "linkedDrivers" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "product_entity" ALTER COLUMN "linkedDrivers" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_entity" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "product_entity" ADD "location" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_entity" DROP COLUMN "rating"`);
        await queryRunner.query(`ALTER TABLE "product_entity" ADD "rating" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_entity" DROP COLUMN "pricePerKg"`);
        await queryRunner.query(`ALTER TABLE "product_entity" ADD "pricePerKg" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_entity" DROP COLUMN "scale"`);
        await queryRunner.query(`DROP TYPE "public"."product_entity_scale_enum"`);
        await queryRunner.query(`ALTER TABLE "product_entity" ADD "scale" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "product_entity" ALTER COLUMN "productId" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "buyer_entity" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "buyer_entity" ADD "userId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "buyer_entity" ALTER COLUMN "isAdmin" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "buyer_entity" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "buyer_entity" ADD "location" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "buyer_entity" DROP CONSTRAINT "UQ_26592e7cae06b9ca8acb493d0b9"`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" DROP COLUMN "buyerId"`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" ADD "buyerId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" DROP COLUMN "purchaseType"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_entity_purchasetype_enum"`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" ADD "purchaseType" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" DROP COLUMN "cylinder"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_entity_cylinder_enum"`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" ADD "cylinder" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" DROP COLUMN "priceType"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_entity_pricetype_enum"`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" ADD "priceType" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" DROP COLUMN "productId"`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" ADD "productId" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "purchase_entity" DROP COLUMN "deliveryFee"`);
        await queryRunner.query(`DROP TABLE "withdrawal_request_entity"`);
        await queryRunner.query(`DROP TABLE "payment_entity"`);
    }

}
